FROM php:7.4-fpm
RUN pecl install xdebug-3.1.5

COPY xdebug/90-xdebug.ini "${PHP_INI_DIR}/conf.d"

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y \
    git \
    pdftk \
    ghostscript \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    libpng-dev
RUN docker-php-ext-install \
    gd \
    zip \
    intl \
    mysqli \
    pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

COPY ./symfony/projectName/ /var/www/symfony/
WORKDIR /var/www/symfony/
